### ISSUE TITLE
Remove All Tab Except Bookmarks And Remove Sync

### ISSUE THREAD

**Issue by ghost** [gwindlord/caf_chromium_m46_build#1]
Hi,

I'm trying to compile this myself, Could you help me out and tell me what would i have to do to remove all tabs except bookmarks and also remove sync?

**Comment by gwindlord** [comment]
Hi,

Removing sync is easy - just do not apply **signin.patch** and that's all.

What is for tabs, this one is more complicated, I cannot clearly imagine how to disable them. Though you can try to look through [this commit](https://codeaurora.org/cgit/quic/chrome4sdp/chromium/src/commit/?h=m46&id=4bc2ed8a216578409931671935c527005c8bef2b), and after you realize how did they do custom New Tab Page, you can probably disable other tabs.

**Comment by ghost** [comment]
Thanks for that,

I've rewritten this comment because I learned a thing or two.

So I started with a fresh so and I’m following your guide, it's now downloading sources...

I still have a couple of questions.

I haven’t done programming in ages so I’m not so confident if it's very complicated. the two things I would like to achieve apart from removing signin that you already showed me.

1.I need a start page like speed dial 2 extension. What would be the easiest way to achieve this on android build?

Can I integrate extensions while building chromium?

if all fails I guess I can just set the homepage to open bookmarks page tab chrome://bookmarks?
1. I would like to clear history on exit if possible? is that easy to do?

**Comment by gwindlord** [comment]
Okay, let me rewrite the comment too then :)

I've never heard about the extensions on the Android Chromium and AFAIK, they are not supported for this platform. Most of special pages, including _chrome://bookmarks_ are unavailable for Android version either.

As for history clearing, I assume this is possible, but almost sure it is not so easy as it seems - I've tried to omit confirmation window on adding word to dictionary, but after two hours of code digging refused that idea. Sometimes it is really complicated and these handlers and listeners logic makes me cry - as I'm not a programmer at all.

**Comment by ghost** [comment]
Finally finished gclient sync but i did get some errors, Tried again with same errors. They seem to be related to web refiner not being available.

If you don't mind could you have a look at my log?

http://pastebin.com/KBz2MMD3

**Comment by gwindlord** [comment]
I've never seen such error, just tried to sync using command _gclient sync -n --no-nag-max_ and everything went fine. You can try to open https://webtech-devx.qualcomm.com/ in browser and will see the page. Maybe connection issue?..

**Comment by ghost** [comment]
Hi dude,

Ok i finally got up to make.sh, the sync just worked today and all went smooth except for:

error: could not revert 2f8a15a... Revamp bookmark UI
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
fatal: unable to stat 'chrome/android/java/src/org/chromium/chrome/browser/ntp/BrowserBookmarksRecyclerView.java': No such file or directory
fatal: unable to stat 'chrome/android/java/src/org/chromium/chrome/browser/ntp/BrowserBookmarksRecyclerView.java': No such file or directory
fatal: unable to stat 'chrome/android/java/src/org/chromium/chrome/browser/ntp/BrowserBookmarksRecyclerView.java': No such file or directory
./build/make.sh: line 54: gclient: command not found
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?

## The text leading up to this was:

|--- out/Release/obj/chrome/chrome_strings_grd.ninja

## |+++ out/Release/obj/chrome/chrome_strings_grd.ninja

File to patch: 

I didn't know what file? so i pressed enter and it asked me if i wanted to skip that patch i did and it finished but i don't have any apk or even the directory src/out

Can you see what the problem is?

I have no idea why some of this comment is bold and large font

**Comment by gwindlord** [comment]
Hi there,

I have an idea about font - this is called markdown :)

Go to _src_ and do _git revert --abort_. Then go up and do _./build/update.sh_ - that should make clean working copy.

What is about the error, it looks like that you've forgot to put depot_tools into PATH - and _make.sh_ assumes they're there.
Also file _chrome/android/java/src/org/chromium/chrome/browser/ntp/BrowserBookmarksRecyclerView.java_ is obviously absent, because the correct file path is _chrome/browser/ntp/BrowserBookmarksRecyclerView.java_ - and it seems that you're in the wrong directory. Correct dirs structure after you cloned my repo and checkouted chromium repo, is:
- .git
- src
- build
- .gclient_entries
- README.md
- .gclient
- chromium.gyp_env

and the _src_ dir here contains the chromium sources. That's why you have to start script from this top dir like _./build/make.sh --no-gclient_ (it is the dry run, without starting actual build).

You can skip that patch file you've mentioned (maybe even comment it out in make.sh), because it contains Russian translation, which may be unnecessary for you.

**Comment by gwindlord** [comment]
As there were no changes within the month, closing the discussion.
